site_name: edgartools
theme:
  name: "readthedocs"

nav:
  - Overview: index.md
  - Filtering: filtering-filings.md
  - Filings: working-with-filings.md
  - Companies: company.md
  - Attachments: attachments.md
  - Financials: company-financials.md
  - XBRL: xbrl.md
  - SGML: sgml.md
  - Data Objects: data-objects.md
  - Local Storage: local-data.md
  - Quick Guide: quick-guide.md
